name: CI

on: [push, pull_request]

jobs:
  test-lint-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache emscripten build
        id: cache-emscripten-build
        uses: actions/cache@v4
        with:
          path: "packages/epanet-engine/dist"
          key: emscrip-${{ hashFiles('packages/epanet-engine/Dockerfile')}}-${{ hashFiles('packages/epanet-engine/build.sh')}}

      - name: list files
        run: ls -LR  packages/epanet-engine
      - name: Build emscripten docker container
        if: steps.cache-emscripten-build.outputs.cache-hit != 'true'
        run: pnpm build:engine

      - name: Get pnpm cache
        id: pnpm-cache
        run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install
      - name: Running tests
        run: pnpm test

      - name: Running test coverage
        run: pnpm test:coverage-ci
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: "packages/epanet-js/test-report.junit.xml"
          fail_ci_if_error: true

      - name: Running build
        run: pnpm build
